# Generated by Django 4.1.1 on 2022-10-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_model', '0003_branch_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('gtin_product', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Gtin product')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('unit_value', models.FloatField(verbose_name='Unit value')),
            ],
        ),
    ]
