# Generated by Django 4.1.2 on 2022-10-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_model', '0005_branch_created_at_branch_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_value',
        ),
    ]
