# Generated by Django 4.1.2 on 2022-10-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_model', '0007_alter_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
    ]
