# Generated by Django 4.1.2 on 2022-10-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_model', '0008_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='gln_branch',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='GLN branch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gtin_product',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Gtin product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gln_user',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='GLN client'),
        ),
    ]
