# Generated by Django 4.1.1 on 2022-10-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='is_active',
        ),
    ]
