# Generated by Django 4.1.1 on 2022-10-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_gln_branch_inventory_gln_branch_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='gln_branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='gln_product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='gln_user_id',
            new_name='user',
        ),
    ]
