# Generated by Django 4.1.1 on 2022-10-09 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_model', '0005_branch_created_at_branch_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_rename_gln_branch_id_inventory_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='user',
        ),
        migrations.AddField(
            model_name='inventory',
            name='gln_branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base_model.branch', verbose_name='GLN branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='gln_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='GLN client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='gtin_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base_model.product', verbose_name='Gtin product'),
            preserve_default=False,
        ),
    ]
